baseurl = "https://nickbrazeau.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Website of Nicholas F. Brazeau"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "medbayes"
    tag = "medicine, bayesian"


[params]
contentratio = 0.7
title = "Nick Brazeau"
copyright = "2021 - {{ YEAR }}"
description = """
Personal website of Nicholas F. Brazeau
MD/PhD Candidate
University of North Carolina School of Medicine, 2023
"""
profilePicture = "images/NFB_Professional_ChimpPic_crop.jpeg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css", "css/styles.css"]
# example ["js/custom.js"]
customJs = []
# Have a static page as a home page
# If you prefer having a static page as your home page rather than a listing of
# the latest posts, then make sure you leave the mainSections parameter blank:
mainSections = ["blog"]
# name posts blogs
postSectionName = "blog"
# images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

# display mode
displayMode = "dark"

# dates
singleDateFormat = "02 Jan"
indexDateFormat = "02 Jan"
listDateFormat = "02 Jan"

# outdated
oldContentWarning = true
oldContentDuration = 365


## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/nickbrazeau/"

[[params.socialIcons]]
icon = "fas fa-pencil-alt"
title = "Pubmed"
url = "https://www.ncbi.nlm.nih.gov/myncbi/1Z38GNVdoiEkg/bibliography/public/"

[[params.socialIcons]]
icon = "fas fa-graduation-cap"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=ZdLn4sUAAAAJ&hl"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCiD"
url = "https://orcid.org/my-orcid?orcid=0000-0003-3976-7965"

[[params.socialIcons]]
icon = "fab fa-researchgate"
title = "Research Gate"
url = "https://www.researchgate.net/profile/Nicholas-Brazeau-2"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/nfbrazeau/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"


[menu]

    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 1
    url = "/"

  [[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about/"

  [[menu.main]]
    name = "Projects & Interests"
    weight = 3
    identifier = "Research"
    url = "/research/"

  [[menu.main]]
    name = "Publications & Talks"
    weight = 4
    identifier = "publications"
    url = "/publications/"


  [[menu.main]]
    name = "Blog"
    weight = 5
    identifier = "blog"
    url = "/blog/"


# outputs for RSS

  [outputs]
    home = ["HTML"]
    section = ["HTML", "RSS"]
    taxonomy = ["HTML"]
    term = ["HTML"]
